"use client";
import {apiFetch,assetPath} from "@/lib/client";
import {useEffect,useRef,useState,type CSSProperties,type FormEvent} from 'react';
import {Leaf,Sprout,ChefHat,Store,Armchair,Users,House,Coins,Package,CloudCheck,CloudOff,LogOut,HelpCircle,ArrowLeft,ArrowRight,Check,Lock,Plus,Gift,Clock,Flame,CupSoda,Flower2,Cookie,Milk,Sun,Copy,KeyRound,RefreshCw,MapPin,ChevronRight,CheckCheck,NotebookPen,Gamepad2,Move,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import {CROPS,RECIPES,DECOR,EXPANSIONS,STAFF,QUESTS,levelOf,levelProgress,timeLeft,plotCount,craftCost,sellPrice,availableRecipes,type Save,type Crop,type Recipe,type Decor,type Role} from '@/lib/game';

type User={id:string;name:string};type Payload={user:User|null;state?:Save;revision?:number;serverNow?:number;message?:string;recovery?:string;error?:string};
type Section='garden'|'kitchen'|'shop'|'decor'|'staff'|'expand';
const NAV=[{id:'garden',label:'田园',icon:Sprout},{id:'kitchen',label:'厨房',icon:ChefHat},{id:'shop',label:'茶馆',icon:Store},{id:'decor',label:'布置',icon:Armchair},{id:'staff',label:'伙伴',icon:Users},{id:'expand',label:'扩建',icon:House}] as const;
const FARM_POSITIONS=[[36,44],[52,54],[68,64],[22,54],[38,64],[54,74]];
const CROP_CLUSTER=[[50,30],[72,48],[28,48],[50,66]];
const POSITIONS=[[24,43],[38,43],[24,59],[38,59],[24,75],[38,75]];
const DECOR_POSITIONS=[[52,39],[65,39],[78,39],[52,52],[65,52],[78,52],[52,65],[65,65],[78,65],[52,78],[65,78],[78,78]];
function Sprite({index,className='',style={}}:{index:number;className?:string;style?:CSSProperties}){return <span aria-hidden="true" className={'sprite '+className} style={{backgroundPosition:`${index%4/3*100}% ${Math.floor(index/4)/3*100}%`,...style}}/>;}
function RecipeIcon({recipe}:{recipe:Recipe}){const Icon={milkTea:Milk,fruitTea:CupSoda,jasmineTea:Flower2,teaCake:Cookie}[recipe];return <span className={'recipe-icon '+recipe}><Icon/></span>;}
function formatSeconds(seconds:number){if(seconds>=3600)return `${Math.floor(seconds/3600)} 小时 ${Math.floor(seconds%3600/60)} 分`;if(seconds>=60)return `${Math.floor(seconds/60)} 分 ${seconds%60} 秒`;return `${seconds} 秒`;}
function Amount({children}:{children:React.ReactNode}){return <span className="amount"><Coins size={15}/>{children}</span>;}
function Hero({hero,className=''}:{hero:Save['hero'];className?:string}){return <span className={'hero-portrait '+className}><img src={assetPath(hero+'.png')} alt={hero==='qingfeng'?'青锋':'灵叶'}/></span>;}

export default function Courtyard(){
 const [user,setUser]=useState<User|null>(null),[state,setState]=useState<Save|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[online,setOnline]=useState(true);
 const [tab,setTab]=useState<Section>('garden'),[seed,setSeed]=useState<Crop>('tea'),[clock,setClock]=useState(Date.now()),[modal,setModal]=useState<'help'|'inventory'|'account'|'journal'|'games'|null>(null);
 const [authMode,setAuthMode]=useState<'register'|'login'|'recover'>('register'),[name,setName]=useState(''),[password,setPassword]=useState(''),[recoveryInput,setRecoveryInput]=useState(''),[authError,setAuthError]=useState(''),[recovery,setRecovery]=useState<string|null>(null),[savedCode,setSavedCode]=useState(false);
 const [decorKind,setDecorKind]=useState<Decor>('table'),[selectedDecor,setSelectedDecor]=useState<string|null>(null),[retryAction,setRetryAction]=useState<Record<string,unknown>|null>(null),[error,setError]=useState('');
 const [menu,setMenu]=useState<Recipe[]>(['milkTea','fruitTea']),[price,setPrice]=useState<Save['price']>('normal');
 const revision=useRef(-1),offset=useRef(0),locked=useRef(false),userId=useRef<string|null>(null);
 const apply=(p:Payload)=>{if(p.serverNow)offset.current=p.serverNow-Date.now();if(p.user){userId.current=p.user.id;setUser(p.user);}if(p.state&&((p.revision??0)>=revision.current)){revision.current=p.revision??0;setState(p.state);}setOnline(true);setError('');};
 async function sync(initial=false){try{const r=await apiFetch(initial?'/api/auth':'/api/game',{cache:'no-store'}),p:Payload=await r.json();if(!r.ok)throw new Error(p.error||'小院暂时连不上');if(initial&&!p.user){setUser(null);setState(null);return;}if(!initial&&!userId.current)return;apply(p);}catch(e){setOnline(false);setError(e instanceof Error?e.message:'网络连接暂时中断');}finally{setLoading(false);}}
 useEffect(()=>{void sync(true);const timer=setInterval(()=>setClock(Date.now()),1000);return ()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!user)return;const timer=setInterval(()=>{if(!locked.current&&!document.hidden)void sync();},12000);const onVisible=()=>{if(!document.hidden&&!locked.current)void sync();};document.addEventListener('visibilitychange',onVisible);return ()=>{clearInterval(timer);document.removeEventListener('visibilitychange',onVisible);};},[user?.id]);
 useEffect(()=>{if(state){setMenu(state.menu);setPrice(state.price);}},[state?.menu.join(','),state?.price]);
 const now=clock+offset.current;
 async function auth(event:FormEvent){event.preventDefault();if(locked.current)return;locked.current=true;setBusy(true);setAuthError('');try{const r=await apiFetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:authMode,name,password,recovery:recoveryInput})}),p:Payload=await r.json();if(!r.ok)throw new Error(p.error||'暂时未能登录');revision.current=-1;apply(p);setPassword('');setRecoveryInput('');if(p.recovery){setRecovery(p.recovery);setSavedCode(false);}toast.success(authMode==='register'?'欢迎，属于你的小院准备好了':'欢迎回家');}catch(e){setAuthError(e instanceof Error?e.message:'网络有点忙，请重试。');}finally{locked.current=false;setBusy(false);}}
 async function act(action:Record<string,unknown>){if(locked.current)return;locked.current=true;setBusy(true);const payload={...action,requestId:action.requestId||crypto.randomUUID()};try{const r=await apiFetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const p:Payload=await r.json();if(!r.ok){if(r.status===401){userId.current=null;setUser(null);setState(null);setAuthMode('login');}setRetryAction(null);throw new Error(p.error||'操作暂时未完成');}apply(p);setRetryAction(null);if(p.message&&!['已保存','操作已完成'].includes(p.message)&&!['offline','help'].includes(String(action.type)))toast.success(p.message);}catch(e){if(e instanceof TypeError){setOnline(false);setRetryAction(payload);toast.error('网络中断，请重试确认上次操作。');}else toast.error(e instanceof Error?e.message:'操作暂时未完成');}finally{locked.current=false;setBusy(false);}}
 async function logout(){if(locked.current)return;locked.current=true;setBusy(true);try{const r=await apiFetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'logout'})});if(!r.ok)throw new Error('暂时无法退出，请重试。');userId.current=null;revision.current=-1;setUser(null);setState(null);setModal(null);setRetryAction(null);setAuthMode('login');}catch(e){toast.error(e instanceof Error?e.message:'网络中断，请重试。');}finally{locked.current=false;setBusy(false);}}
 async function copyCode(){try{await navigator.clipboard.writeText(recovery||'');setSavedCode(true);toast.success('找回码已复制，请存到安全的地方');}catch{toast.error('请长按找回码手动复制');}}
 const disabled=busy||!!retryAction;
 const sceneBg={backgroundImage:`url(${assetPath('courtyard-background.png')})`};
 const recoverDialog=<Dialog open={!!recovery} onOpenChange={()=>{}}><DialogContent showCloseButton={false} className="paper-dialog"><DialogHeader><span className="modal-symbol"><KeyRound/></span><DialogTitle>收好小院的备用钥匙</DialogTitle><DialogDescription>不绑定邮箱，这份找回码就是重设密码的凭证。请复制保存；离开这里后不会再次显示。</DialogDescription></DialogHeader><code className="recovery-code">{recovery}</code><Button onClick={copyCode} className="outline-button"><Copy/>复制找回码</Button><label className="check-label"><Checkbox checked={savedCode} onCheckedChange={v=>setSavedCode(v===true)}/>我已经把找回码保存在安全的地方</label><Button disabled={!savedCode} onClick={()=>setRecovery(null)}>收好了，回到小院 <ArrowRight/></Button></DialogContent></Dialog>;
 const toaster=<Toaster position="top-center" richColors toastOptions={{style:{fontFamily:'inherit'}}}/>;
 if(!user||!state)return <main className="arrival" style={sceneBg}><div className="arrival-shade"/><a className="back-game" href="https://yu-hao-0323.github.io/tea-garden-breakout/"><ArrowLeft size={16}/> 茶园突围</a><div className="arrival-title"><span className="arrival-mark"><Leaf size={25}/></span><p>山间小院</p><h1>种一院清欢，<br/>待一盏茶香。</h1><span className="arrival-caption"><Sprout size={17}/> 种植 · 制茶 · 开店 · 布置小院</span></div><section className="auth-card"><div className="auth-heading"><span className="eyebrow">你的小院，等你回来</span><h2>{authMode==='recover'?'找回小院':authMode==='register'?'成为小院主人':'欢迎回家'}</h2></div>{authMode!=='recover'&&<Tabs value={authMode} onValueChange={v=>{setAuthMode(v as 'login'|'register');setAuthError('');}}><TabsList className="auth-tabs"><TabsTrigger value="register">初来乍到</TabsTrigger><TabsTrigger value="login">回到小院</TabsTrigger></TabsList></Tabs>}<form onSubmit={auth}><label htmlFor="account-name">你的名字</label><Input id="account-name" value={name} onChange={e=>setName(e.target.value)} autoComplete="username" maxLength={20} placeholder="给小院留一个名字" required/>{authMode==='recover'&&<><label htmlFor="recovery-input">找回码</label><Input id="recovery-input" value={recoveryInput} onChange={e=>setRecoveryInput(e.target.value)} placeholder="注册时保存的备用钥匙" autoComplete="off" required/></>}<label htmlFor="account-password">{authMode==='recover'?'新密码':'密码'}</label><Input id="account-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={authMode==='login'?'current-password':'new-password'} minLength={8} maxLength={72} placeholder="至少 8 个字符" required/>{authError&&<p role="alert" className="form-error">{authError}</p>}<Button className="enter-button" disabled={busy||loading} type="submit">{busy?'正在开门…':loading?'正在查看小院…':authMode==='register'?'开启我的小院':authMode==='login'?'回到我的小院':'重设密码，回到小院'}<ArrowRight size={18}/></Button></form><p className="auth-note">只需名字和密码，无需邮箱。<br/>小院自动存档，换设备登录也能接着玩。</p><button className="text-button" onClick={()=>{setAuthMode(authMode==='recover'?'login':'recover');setAuthError('');}}>{authMode==='recover'?'返回登录':'忘记密码？用找回码开门'}</button>{error&&<p className="connection-error">{error}<button onClick={()=>sync(true)}>重试连接</button></p>}</section><div className="arrival-footer"><Sun size={16}/> 山风正好，不必着急</div>{recoverDialog}{toaster}</main>;
 const lv=levelProgress(state.xp),readyPlots=state.plots.filter((p,i)=>i<plotCount(state)&&p.crop&&p.readyAt<=now).length,nextExpansion=EXPANSIONS[state.tier];
 const mainQuest=QUESTS.findIndex((q,i)=>!state.claimed.includes(i)),quest=QUESTS[mainQuest];
 const choosePlace=(slot:number)=>{if(selectedDecor)void act({type:'moveDecor',id:selectedDecor,slot});else void act({type:'decorate',kind:decorKind,slot});};
 const panelHeading={garden:['田园日常','种下喜欢的，慢慢等它长大。'],kitchen:['一口小厨房','把今天的收获，做成热乎的茶点。'],shop:['山间茶馆','为每一位来客，备一份心意。'],decor:['布置我的小院','选一件心仪的摆设，再点院里的空位。'],staff:['小院的伙伴','人多一点，日子就轻松一点。'],expand:['把日子慢慢铺开','从一方茶摊，到一处山间归宿。']}[tab];
 return <main className="game-shell">{toaster}<header className="game-header"><button className="brand-lockup" onClick={()=>setModal('games')} title="游戏入口"><span><Leaf/></span><div><strong>山间小院</strong><small>山色正好 · 茶香正浓</small></div></button><div className="resource-bar"><div className="coin-resource"><Coins/><span><small>小院金币</small><b>{state.coins.toLocaleString()}</b></span></div><button className="level-resource" onClick={()=>setModal('journal')}><span>Lv.{lv.level}</span><div><small>{state.tier?EXPANSIONS[state.tier-1].name:'初见小茶摊'}</small><Progress value={lv.current/lv.total*100}/></div></button></div><div className="header-tools"><span className={'save-status '+(!online?'offline':'')}>{online?<CloudCheck size={15}/>:<CloudOff size={15}/>}<span>{busy?'正在保存':online?'进度已保存':'连接中断'}</span></span><button className="icon-button" title="仓库" aria-label="打开仓库" onClick={()=>setModal('inventory')}><Package/></button><button className="owner-button" aria-label="账号与店主" onClick={()=>setModal('account')}><Hero hero={state.hero}/></button></div></header>
 {(retryAction||error)&&<div role="alert" className="sync-banner"><CloudOff size={16}/>{retryAction?'上次操作尚未确认。重试不会重复扣款。':error}<button onClick={()=>retryAction?act(retryAction):sync()} disabled={busy}>{busy?'正在确认…':'重试确认'}</button></div>}
 <div className="game-layout"><section className="yard-pane"><div className="yard-heading"><div><span className="eyebrow">{user.name}的小院</span><h1>{tab==='decor'?'在这里，摆下喜欢的生活。':'今天，也有小小的收获。'}</h1></div><span className="weather-pill"><Sun size={16}/> 晴 · 风和日暖</span></div><div className={'yard-scene '+(tab==='garden'?'farm-scene ':'')+(tab==='decor'?'decorating ':'')+(state.tier>=4?'has-market':'')} style={tab==='garden'?{backgroundImage:`url(${assetPath('farm-map-v2.png')})`}:sceneBg}><span className="scene-label"><MapPin size={13}/>{state.tier?EXPANSIONS[state.tier-1].name:'山间小茶摊'}</span><button className={'shop-sign '+(state.open?'open':'')} onClick={()=>{setTab('shop');}}><span>{state.open?'营业中':'歇业中'}</span><small>{state.orders.length} 位客人等候 <ChevronRight size={12}/></small></button>
 {state.plots.map((p,i)=>{const lockedPlot=i>=plotCount(state),mature=!!p.crop&&p.readyAt<=now,growth=p.crop?Math.min(1,1-(p.readyAt-now)/(CROPS[p.crop].seconds*1000)):0;return <button key={i} style={{left:(tab==='garden'?FARM_POSITIONS:POSITIONS)[i][0]+'%',top:(tab==='garden'?FARM_POSITIONS:POSITIONS)[i][1]+'%',zIndex:Math.round((tab==='garden'?FARM_POSITIONS:POSITIONS)[i][1])}} className={'plot '+(tab==='garden'?'farm-plot ':'')+(mature?'mature ':'')+(lockedPlot?'locked-plot ':'')+(!p.crop?'empty-plot':'')} disabled={disabled||tab==='decor'||(!!p.crop&&!mature)} aria-label={lockedPlot?'扩建解锁田地':p.crop?CROPS[p.crop].name+(mature?'已成熟，点击采收':'生长中'):'空田，点击种下'+CROPS[seed].name} onClick={()=>lockedPlot?setTab('expand'):act(p.crop?{type:'harvest',index:i}:{type:'plant',index:i,crop:seed})}>{tab==='garden'&&<span className="soil-tile" aria-hidden="true"><span className="soil-ridges"/></span>}{lockedPlot?<Lock className="plot-lock"/>:p.crop?<>{tab==='garden'?<span className={'crop-cluster '+(growth<.25?'seedling-stage':growth<.8?'growing-stage':'ripe-stage')}>{CROP_CLUSTER.map(([x,y],n)=><span key={n} className="crop-plant" style={{left:x+'%',top:y+'%',zIndex:Math.round(y),transform:`translate(-50%,-82%) scale(${mature?1:.35+growth*.6})`}}>{growth<.25&&!mature?<Sprout/>:<Sprite index={CROPS[p.crop!].sprite}/>}</span>)}</span>:<Sprite index={CROPS[p.crop].sprite} className="crop-sprite" style={{transform:`translateX(-50%) scale(${.48+growth*.52})`}}/>}<span className="crop-badge">{mature?<><Check size={12}/>{tab==='garden'?CROPS[p.crop].name+' · 可收获':'采收'}</>:formatSeconds(timeLeft(p.readyAt,now))}</span></>:<><Plus className="plot-plus"/><span className="empty-label">播种</span></>}</button>;})}
 {state.decor.map(d=><button key={d.id} className={'placed-decor '+(['cat','dog'].includes(d.kind)?'pet-decor ':'')+(selectedDecor===d.id?'selected-decor':'')} style={{left:DECOR_POSITIONS[d.slot][0]+'%',top:DECOR_POSITIONS[d.slot][1]+'%'}} title={DECOR[d.kind].name} aria-label={DECOR[d.kind].name+(tab==='decor'?'，选中移动':'' )} onClick={()=>{if(tab==='decor'){setSelectedDecor(d.id);setDecorKind(d.kind);}else if(['cat','dog'].includes(d.kind))toast(DECOR[d.kind].name+' 靠过来蹭了蹭你');}}><Sprite index={DECOR[d.kind].sprite}/></button>)}
 {tab==='decor'&&DECOR_POSITIONS.map((pos,i)=>!state.decor.some(d=>d.slot===i)&&<button key={i} className="decor-slot" style={{left:pos[0]+'%',top:pos[1]+'%'}} disabled={disabled} aria-label={'摆放位置 '+(i+1)} onClick={()=>choosePlace(i)}><Plus size={17}/></button>)}
 {state.tier>=2&&<button className="expansion-sprite guest-house" onClick={()=>setTab('expand')} aria-label="山居客房"><Sprite index={10}/></button>}{state.tier>=3&&<button className="expansion-sprite hot-spring" onClick={()=>setTab('expand')} aria-label="山泉温汤"><Sprite index={11}/></button>}{state.tier>=4&&<button className="expansion-sprite night-market" onClick={()=>setTab('shop')} aria-label="夜市茶摊"><Sprite index={12}/></button>}
 {tab!=='decor'&&<div className="scene-owner"><Hero hero={state.hero}/><span>{state.hero==='qingfeng'?'青锋':'灵叶'} · 店主</span></div>}
 <div className="scene-bottom"><span><Leaf size={14}/>{tab==='decor'?(selectedDecor?'点空位挪动，也可以在右侧收起。':'选好摆设后，点 + 放进小院。'):'点击成熟的作物采收，点击空田播种。'}</span><button aria-label="玩法说明" onClick={()=>setModal('help')}><HelpCircle size={18}/></button></div></div>
 <div className="yard-bottom">{tab==='decor'?<div className="placement-bar"><Sprite index={DECOR[decorKind].sprite}/><div><strong>{selectedDecor?'正在挪动：':'准备摆放：'}{DECOR[decorKind].name}</strong><small>{selectedDecor?'选择空位即可移动':'点院里的 +，扣除 '+DECOR[decorKind].cost+' 金币'}</small></div>{selectedDecor&&<button className="text-button" onClick={()=>setSelectedDecor(null)}>取消选择</button>}</div>:<div className="seed-bar"><span className="seed-heading"><Sprout size={17}/>播种</span>{(Object.keys(CROPS) as Crop[]).map(c=><button key={c} className={'seed-choice '+(seed===c?'chosen':'')} onClick={()=>{setSeed(c);setTab('garden');}}><Sprite index={CROPS[c].sprite}/><span>{CROPS[c].name}<small>{CROPS[c].seed} 金币</small></span></button>)}<button className="harvest-all" disabled={!readyPlots||disabled} onClick={()=>act({type:'harvestAll'})}><CheckCheck size={18}/><span>一键采收<small>{readyPlots?readyPlots+' 块已成熟':'作物生长中'}</small></span></button></div>}
 {quest&&<button className={'quest-strip '+(state[quest.key]>=quest.goal?'claimable':'')} disabled={disabled} onClick={()=>state[quest.key]>=quest.goal?act({type:'quest',index:mainQuest}):setModal('journal')}><span className="quest-icon"><Gift size={18}/></span><div><strong>{quest.title}</strong><small>{quest.description} · {Math.min(quest.goal,state[quest.key])}/{quest.goal}</small></div><Amount>+{quest.reward}</Amount><span className="quest-action">{state[quest.key]>=quest.goal?'领取':'查看'}<ChevronRight size={14}/></span></button>}</div>
 </section>
 <aside className="management-pane"><div className="panel-title"><span className="eyebrow">{NAV.find(n=>n.id===tab)?.label}手记</span><h2>{panelHeading[0]}</h2><p>{panelHeading[1]}</p></div><div className="panel-scroll">
 {tab==='garden'&&<><div className="garden-overview"><Sprite index={CROPS[seed].sprite}/><div><small>手里的种子</small><h3>{CROPS[seed].name}</h3><p>{CROPS[seed].seconds} 秒成熟 · 收获 {CROPS[seed].yield} 份</p><Amount>{CROPS[seed].seed} / 块</Amount></div></div><div className="section-heading"><h3>仓库里的新鲜收获</h3><button className="text-button" onClick={()=>setModal('inventory')}>查看全部</button></div><div className="ingredient-grid">{(Object.keys(CROPS) as Crop[]).map(c=><div key={c}><Sprite index={CROPS[c].sprite}/><span>{CROPS[c].name}<strong>{state.inventory[c]}</strong></span></div>)}</div><Button className="wide-action" onClick={()=>setTab('kitchen')}><ChefHat/>带着收获去厨房 <ArrowRight size={16}/></Button><div className="soft-note"><Clock size={18}/><p>离开时作物也会继续生长，成熟后一直等你，不会枯萎。</p></div><div className="section-heading"><h3>小院近况</h3><span>慢慢变好</span></div>{state.recent.length?state.recent.slice(0,4).map(n=><div className="activity-row" key={n.id}><span/><p>{n.text}</p></div>):<p className="empty-copy">两块田已经成熟了，去收下第一份礼物吧。</p>}{state.coins<15&&<Button className="outline-button" onClick={()=>act({type:'gift'})} disabled={disabled}><Gift/>领取邻里援助</Button>}</>}
 {tab==='kitchen'&&<><div className="stove-status"><Flame size={18}/><span>灶台 {state.jobs.length}/{2+state.equipment}</span><small>{state.equipment?'手艺灶 Lv.'+state.equipment:'朴素的好味道'}</small></div>{state.jobs.length>0&&<div className="cooking-list">{state.jobs.map(j=><div key={j.id}><RecipeIcon recipe={j.recipe}/><div><strong>{RECIPES[j.recipe].name}</strong><small>{timeLeft(j.readyAt,now)?formatSeconds(timeLeft(j.readyAt,now))+' 后出锅':'即将出锅'}</small><Progress value={Math.max(0,100-timeLeft(j.readyAt,now)/RECIPES[j.recipe].seconds*100)}/></div></div>)}</div>}{(Object.keys(RECIPES) as Recipe[]).map(k=>{const r=RECIPES[k],unlocked=lv.level>=r.level;return <article key={k} className={'recipe-card '+(!unlocked?'card-locked':'')}><div className="recipe-top"><RecipeIcon recipe={k}/><div><h3>{r.name}</h3><p>{r.description}</p></div>{!unlocked&&<span className="level-lock"><Lock size={11}/>Lv.{r.level}</span>}</div><div className="recipe-ingredients">{Object.entries(r.ingredients).map(([c,n])=><span className={state.inventory[c as Crop]<n?'shortage':''} key={c}>{CROPS[c as Crop].name} {n}<small> / {state.inventory[c as Crop]}</small></span>)}</div><div className="recipe-meta"><span>辅料 <Amount>{r.cost}</Amount> · {r.seconds} 秒</span><span>成品 {state.goods[k]} 份</span></div><Button disabled={disabled||!unlocked||!craftCost(state,k)||state.jobs.length>=2+state.equipment} onClick={()=>act({type:'cook',recipe:k})} className="recipe-cook">{!unlocked?'经营 Lv.'+r.level+' 解锁':!craftCost(state,k)?'材料或金币不足':'制作一份'}{unlocked&&<ChefHat size={16}/>}</Button></article>;})}</>}
 {tab==='shop'&&<><div className="business-bar"><span className={state.open?'is-open':''}><i/>{state.open?'茶香迎客':'暂时歇业'}</span><Button className="outline-button small-button" disabled={disabled} onClick={()=>act({type:'open'})}>{state.open?'歇一会儿':'开门营业'}</Button></div><div className="section-heading"><h3>等候的客人</h3><span>{state.orders.length}/3</span></div>{state.orders.length?state.orders.map((o,i)=><article className="order-card" key={o.id}><div className="order-guest"><span className={'guest-avatar guest-'+i}>{o.guest.slice(-1)}</span><div><strong>{o.guest}</strong><small>{['“一杯热茶，慢慢喝。”','“今天有什么好味道？”','“这个院子真舒服。”'][i%3]}</small></div></div><div className="order-item"><RecipeIcon recipe={o.recipe}/><span>{RECIPES[o.recipe].name} ×{o.quantity}</span><Amount>+{o.payment}</Amount></div><Button disabled={disabled||!state.open||state.goods[o.recipe]<o.quantity} onClick={()=>act({type:'serve',id:o.id})}>{!state.open?'开门后招待':state.goods[o.recipe]<o.quantity?'等待厨房备好':'递上茶点'}<ArrowRight size={15}/></Button></article>):<div className="quiet-empty"><Store/><p>{state.open?'小院正在等下一位来客':'挂好菜单，开门迎客吧。'}</p><small>客人不会催促，也没有超时惩罚。</small></div>}<div className="menu-card"><h3><NotebookPen size={18}/>今日菜单</h3>{availableRecipes(state).map(k=><label key={k} className="menu-choice"><Checkbox checked={menu.includes(k)} onCheckedChange={v=>setMenu(v?[...menu,k]:menu.filter(x=>x!==k))}/><span>{RECIPES[k].name}</span><Amount>{Math.round(RECIPES[k].price*(price==='kind'?.85:price==='premium'?1.25:1)*(state.tier>=4?1.15:1))}</Amount></label>)}<label className="field-label">定价方式</label><Select value={price} onValueChange={v=>setPrice(v as Save['price'])}><SelectTrigger className="full-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="kind">街坊价 · 客人来得快</SelectItem><SelectItem value="normal">平常价 · 刚刚好</SelectItem><SelectItem value="premium">精品价 · 慢一点，赚多一点</SelectItem></SelectContent></Select><Button className="outline-button" disabled={disabled||!menu.length} onClick={()=>act({type:'menu',menu,price})}>挂上新菜单</Button>{state.tier>=4&&<p className="bonus-note">灯火夜市已开，所有茶点收入 +15%</p>}</div></>}
 {tab==='decor'&&<>{selectedDecor&&<div className="selected-item-card"><Move size={18}/><span>选中了{DECOR[decorKind].name}</span><button title="收起并返还70%金币" onClick={()=>{void act({type:'sellDecor',id:selectedDecor});setSelectedDecor(null);}} disabled={disabled}><Trash2 size={17}/></button></div>}<div className="decor-grid">{(Object.keys(DECOR) as Decor[]).map(k=><button key={k} className={'decor-card '+(decorKind===k&&!selectedDecor?'chosen':'')} disabled={lv.level<DECOR[k].level} onClick={()=>{setDecorKind(k);setSelectedDecor(null);}}><Sprite index={DECOR[k].sprite}/><strong>{DECOR[k].name}</strong>{lv.level<DECOR[k].level?<span className="level-lock"><Lock size={12}/>Lv.{DECOR[k].level}</span>:<Amount>{DECOR[k].cost}</Amount>}</button>)}</div><div className="soft-note"><Armchair size={19}/><p>{DECOR[decorKind].description}<br/>点已摆好的物件可移动；收起返还 70% 金币。</p></div></>}
 {tab==='staff'&&<><div className="soft-note"><Users size={20}/><p>伙伴每 20 秒照看一次小院。招募只付一次金币，没有每日工资。</p></div>{STAFF.map(person=>{const hired=state.staff.find(s=>s.id===person.id);return <article className="staff-card" key={person.id}><div className="staff-header"><span className="staff-avatar" style={{background:person.color}}>{person.name.slice(-1)}</span><div><h3>{person.name}</h3><p>{person.title}</p></div>{hired&&<span className="hired-tag">已加入</span>}</div>{hired?<Select value={hired.role} onValueChange={role=>act({type:'assign',id:person.id,role})} disabled={disabled}><SelectTrigger className="full-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="farmer">种植 · 自动采收与播种</SelectItem><SelectItem value="cook">制作 · 自动烹饪茶点</SelectItem><SelectItem value="server">服务 · 自动完成订单</SelectItem><SelectItem value="rest">休息 · 暂不安排</SelectItem></SelectContent></Select>:<Button disabled={disabled||lv.level<person.level||state.coins<person.cost} onClick={()=>act({type:'hire',id:person.id})}>{lv.level<person.level?'Lv.'+person.level+' 可招募':<>招募伙伴 <Amount>{person.cost}</Amount></>}</Button>}</article>;})}{state.staff.length>0&&<div className="menu-card"><h3>交给伙伴的事</h3><label className="field-label">种植伙伴优先播种</label><Select value={state.autoCrop} onValueChange={crop=>act({type:'automation',crop,recipe:state.autoRecipe})} disabled={disabled}><SelectTrigger className="full-select"><SelectValue/></SelectTrigger><SelectContent>{(Object.keys(CROPS) as Crop[]).map(c=><SelectItem key={c} value={c}>{CROPS[c].name}</SelectItem>)}</SelectContent></Select><label className="field-label">厨房伙伴优先制作</label><Select value={state.autoRecipe} onValueChange={recipe=>act({type:'automation',recipe,crop:state.autoCrop})} disabled={disabled}><SelectTrigger className="full-select"><SelectValue/></SelectTrigger><SelectContent>{availableRecipes(state).map(k=><SelectItem key={k} value={k}>{RECIPES[k].name}</SelectItem>)}</SelectContent></Select><p className="field-note">金币至少保留 25 枚；成品超过 20 份时会歇一歇。离线最多照看 8 小时。</p></div>}</>}
 {tab==='expand'&&<>{state.tier>=2&&<div className="service-bank"><House/><div><small>客房与温泉收入</small><strong>{state.serviceBank} 金币</strong></div><Button onClick={()=>act({type:'claimService'})} disabled={disabled||!state.serviceBank}>领取</Button></div>}{EXPANSIONS.map((e,i)=><article key={e.name} className={'expansion-card '+(state.tier>i?'complete':state.tier===i?'next':'future')}><Sprite index={e.sprite}/><div><span className="eyebrow">第 {i+1} 步</span><h3>{e.name}</h3><p>{e.description}</p>{state.tier>i?<span className="completed-tag"><Check size={14}/>已经落成</span>:<Button disabled={disabled||state.tier!==i||lv.level<e.level||state.coins<e.cost} onClick={()=>act({type:'expand'})}>{state.tier!==i?'先完成前一步':lv.level<e.level?'Lv.'+e.level+' 可扩建':<>扩建 <Amount>{e.cost}</Amount></>}</Button>}</div></article>)}<div className="equipment-card"><ChefHat/><div><h3>给厨房添一口好灶</h3><p>多一个制作位，时间缩短 12%</p></div><Button className="outline-button" disabled={disabled||state.equipment>=2||state.coins<180+state.equipment*220} onClick={()=>act({type:'equipment'})}>{state.equipment>=2?'已满级':<Amount>{180+state.equipment*220}</Amount>}</Button></div></>}
 </div></aside></div>
 <nav className="bottom-nav" aria-label="小院功能"><Tabs value={tab} onValueChange={v=>{setTab(v as Section);setSelectedDecor(null);}}><TabsList className="game-tabs">{NAV.map(n=><TabsTrigger key={n.id} value={n.id}><n.icon size={21}/><span>{n.label}</span>{n.id==='garden'&&readyPlots>0&&<i className="nav-count">{readyPlots}</i>}{n.id==='shop'&&state.orders.some(o=>state.goods[o.recipe]>=o.quantity)&&<i className="nav-ready"/>}</TabsTrigger>)}</TabsList></Tabs><button className="journal-button" onClick={()=>setModal('journal')}><NotebookPen size={20}/><span>小院手账</span></button></nav>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v)setModal(null);}}><DialogContent className="paper-dialog"><DialogHeader><DialogTitle>{({help:'慢慢经营你的小院',inventory:'小院仓库',account:'小院主人',journal:'把日子记下来',games:'我们的游戏小屋'} as const)[modal||'help']}</DialogTitle><DialogDescription>{modal==='account'?'换一位店主，继续你的山间日常。':modal==='inventory'?'采收和制作完成后，会自动放进这里。':modal==='journal'?'完成一件小事，就离理想的小院更近一点。':modal==='games'?'选一扇门，开始今天的冒险。':'先收获，再制作，把热乎茶点递给来客。'}</DialogDescription></DialogHeader>
 {modal==='help'&&<div className="help-steps">{[['1','种植采收','在下方选择种子，点击空田播种。成熟后点击作物采收。'],['2','制作茶点','到厨房用原料制作，成品会自动入库。'],['3','招待客人','到茶馆递上所需茶点，赚取金币和经营经验。'],['4','装点生活','用金币买摆设、招募伙伴、扩建小院。'],['5','放心离开','进度自动同步到账号；离线成长最多计算 8 小时。']].map(([n,t,d])=><div key={n}><b>{n}</b><span><strong>{t}</strong><p>{d}</p></span></div>)}<Button onClick={()=>{void act({type:'help'});setModal(null);}}>去收获第一片茶叶</Button></div>}
 {modal==='inventory'&&<><h3 className="section-title">新鲜原料</h3><div className="ingredient-grid">{(Object.keys(CROPS) as Crop[]).map(c=><div key={c}><Sprite index={CROPS[c].sprite}/><span>{CROPS[c].name}<strong>{state.inventory[c]}</strong></span></div>)}</div><h3 className="section-title">备好的茶点</h3><div className="goods-grid">{(Object.keys(RECIPES) as Recipe[]).map(k=><div key={k}><RecipeIcon recipe={k}/><span>{RECIPES[k].name}</span><strong>{state.goods[k]}</strong></div>)}</div></>}
 {modal==='account'&&<><div className="account-name"><Hero hero={state.hero}/><span><strong>{user.name}</strong><small>Lv.{lv.level} · {state.tier?EXPANSIONS[state.tier-1].name:'小茶摊主人'}</small></span></div><div className="hero-choices">{(['qingfeng','lingye'] as const).map(h=><button key={h} className={state.hero===h?'chosen':''} disabled={disabled} onClick={()=>act({type:'hero',hero:h})}><Hero hero={h}/><span>{h==='qingfeng'?'青锋':'灵叶'}</span>{state.hero===h&&<Check size={16}/>}</button>)}</div><div className="soft-note"><CloudCheck size={19}/><p>名字和密码就是小院钥匙。换设备时使用同一个名字登录，即可接着玩。</p></div><Button className="outline-button" onClick={logout} disabled={busy}><LogOut size={17}/>保存并退出账号</Button></>}
 {modal==='journal'&&<><div className="journal-stats"><div><b>{state.sold}</b><span>售出茶点</span></div><div><b>{state.harvested}</b><span>采收作物</span></div><div><b>{state.revenue}</b><span>累计收入</span></div></div>{QUESTS.map((q,i)=><div className="quest-line" key={q.title}><span className={'quest-status '+(state.claimed.includes(i)?'done':'')}>{state.claimed.includes(i)?<Check size={17}/>:i+1}</span><div><strong>{q.title}</strong><p>{q.description} · {Math.min(q.goal,state[q.key])}/{q.goal}</p></div><Button className="outline-button small-button" disabled={disabled||state.claimed.includes(i)||state[q.key]<q.goal} onClick={()=>act({type:'quest',index:i})}>{state.claimed.includes(i)?'已领取':<Amount>+{q.reward}</Amount>}</Button></div>)}</>}
 {modal==='games'&&<div className="game-door-list"><button onClick={()=>setModal(null)}><Sprout/><span><strong>山间小院</strong><small>种植 · 制茶 · 休闲经营</small></span><span className="current-game">正在游玩</span></button><a href="https://yu-hao-0323.github.io/tea-garden-breakout/"><Gamepad2/><span><strong>茶园突围</strong><small>双生守护 · 动作生存</small></span><ArrowRight/></a></div>}
 </DialogContent></Dialog>
 <Dialog open={!!state.offline&&!recovery} onOpenChange={v=>{if(!v)void act({type:'offline'});}}><DialogContent className="paper-dialog"><DialogHeader><span className="modal-symbol"><Sun/></span><DialogTitle>欢迎回来，小院一切都好</DialogTitle><DialogDescription>你离开时，小院照常生长。最多累计 8 小时，成熟作物会一直等你。</DialogDescription></DialogHeader>{state.offline&&<><div className="offline-stats"><div><strong>{Math.floor(state.offline.seconds/60)} 分钟</strong><small>本次照看</small></div><div><strong>{state.offline.coins>=0?'+':''}{state.offline.coins}</strong><small>金币变化</small></div><div><strong>{state.offline.harvested}</strong><small>伙伴采收</small></div><div><strong>{state.offline.served}</strong><small>完成订单</small></div></div><p className="field-note">收入、材料与成品已经自动放进存档，不会重复领取。</p><Button disabled={disabled} onClick={()=>act({type:'offline'})}>回院子看看 <ArrowRight/></Button></>}</DialogContent></Dialog>
 {recoverDialog}
 </main>;
}
